config/routes.rb
Rails.application.routes.draw do
  root 'marknoce#homepage'

  get '/homepage' => 'marknoce#homepage'
  get '/about' => 'marknoce#about'
  get '/books' => 'marknoce#books'
  get '/blog' => 'marknoce#blog'
  get '/appearances' => 'marknoce#appearances'
  get '/contact' => 'marknoce#contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/marknoce_controller.rb
class MarknoceController < ApplicationController

  def homepage
  end

  def about
  end

  def books
  end

  def blog
  end

  def appearances
  end

  def contact
  end

  def email
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MarkNoce</title>
  <link rel="shortcut icon" href="/assets/marknoce.ico" type="image/x-icon" />
  <link href='https://fonts.googleapis.com/css?family=Uncial+Antiqua' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="https://www.googleapis.com/blogger/v3/blogs/8458581324926992168/posts?callback=handleResponse&key=AIzaSyBPO9bgsBJ4Iw2R2Pcj8JZWrOMejLUz5AA"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "navbar" %>
  <%= yield %>
</body>
</html>

app/views/marknoce/_bottomsocialnav.html.erb
<div class="bottom-nav">
  <a href="https://www.facebook.com/markchristophernoce" target="_blank" title="facebook"><div class="bottom-nav-btn">
    <%= image_tag 'rsz_facebook.jpg' %>
  </div></a>
  <a href="https://twitter.com/MarkNoce" target="_blank" title="twitter"><div class="bottom-nav-btn">
    <%= image_tag 'rsz_twitter.jpg' %>
  </div></a>
  <a href="https://www.linkedin.com/in/mark-noce-80345b1a" target="_blank" title="linkedin"><div class="bottom-nav-btn">
    <%= image_tag 'rsz_linkedin.jpg' %>
  </div></a>
  <a href="https://plus.google.com/+MarkNoce" target="_blank" title="google+"><div class="bottom-nav-btn">
    <%= image_tag 'rsz_googleplus.jpg' %>
  </div></a>
  <a href="https://www.goodreads.com/book/show/23172410-between-two-fires" title="goodreads"><div class="bottom-nav-btn" target="_blank">
    <%= image_tag 'rsz_goodreads.jpg' %>
  </div></a>
</div>

app/views/marknoce/_message.html.erb
<div class="modal fade" id="message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Leave a Message</h4>
      </div>
      <div class="modal-body">

        <form action="MAILTO:lawlessdrag0n@gmail.com" method="post" enctype="multipart/form-data">

          Your Name:<br>
          <input type="text" size="20" name="Name"><br><br>
          Your Email:<br>
          <input type="text" size="20" name="Email"><br><br>
          Comment:<br>
          <textarea name="body" rows="5" cols="40">
          </textarea><br><br>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="submit" class="btn" value="Send">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/marknoce/_navbar.html.erb
<%= render partial: "newsletter" %>
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/homepage" class="navbar-brand large regular">Mark Noce</a>
    </div>
    <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
      <ul class="nav navbar-nav nav">
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
        <li>
          <%= link_to "Blog", blog_path %>
        </li>
        <li>
          <%= link_to "Appearances", appearances_path %>
        </li>
        <li>
          <%= link_to "Contact", contact_path %>
        </li>
        <li>
          <a href="#" data-toggle="modal" data-target="#newsletter">Newsletter</a>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/marknoce/_newsletter.html.erb
<div class="modal fade" id="newsletter" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Sign Up for Our Newsletter!</h4>
      </div>
      <div class="modal-body">
        <p>
          Sign up for my newsletter so you can get all the latest news on my work and for my promotional schedule.
        </p>
        <!-- Begin MailChimp Signup Form -->
        <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
        <style type="text/css">
          #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
        </style>
        <div id="mc_embed_signup">
          <form action="//marknoce.us12.list-manage.com/subscribe/post?u=165580dfec698bd7c61029229&amp;id=dc20bdfbca" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
              <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
              <div class="mc-field-group">
                <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
              </label>
                <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
              </div>
              <!-- <div class="mc-field-group">
                <label for="mce-FNAME">First Name </label>
                <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
              </div>
              <div class="mc-field-group">
                <label for="mce-LNAME">Last Name </label>
                <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
              </div> -->
              <div id="mce-responses" class="clear">
                <div class="response" id="mce-error-response" style="display:none"></div>
                <div class="response" id="mce-success-response" style="display:none"></div>
              </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_165580dfec698bd7c61029229_dc20bdfbca" tabindex="-1" value=""></div>

                <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-default" data-dismiss="modal">Close</button></div>
            </div>
          </form>
        </div>
        <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'>
        </script><script type='text/javascript'>
          (function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));
          var $mcj = jQuery.noConflict(true);
        </script>
        <!--End mc_embed_signup-->
      </div>
    </div>
  </div>
</div>

app/views/marknoce/_socialnav.html.erb
<div class="side-nav">
  <a href="https://www.facebook.com/MarkNoce/?fref=ts" target="_blank" title="facebook"><div class="side-nav-btn">
    <%= image_tag 'rsz_facebook.jpg' %>
  </div></a>
  <a href="https://twitter.com/MarkNoce" target="_blank" title="twitter"><div class="side-nav-btn">
    <%= image_tag 'rsz_twitter.jpg' %>
  </div></a>
  <a href="https://www.linkedin.com/in/mark-noce-80345b1a" target="_blank" title="linkedin"><div class="side-nav-btn">
    <%= image_tag 'rsz_linkedin.jpg' %>
  </div></a>
  <a href="https://plus.google.com/+MarkNoce" target="_blank" title="google+"><div class="side-nav-btn">
    <%= image_tag 'rsz_googleplus.jpg' %>
  </div></a>
  <a href="https://www.goodreads.com/book/show/23172410-between-two-fires" title="goodreads"><div class="side-nav-btn" target="_blank">
    <%= image_tag 'rsz_goodreads.jpg' %>
  </div></a>
</div>

app/views/marknoce/_thunderclap.html.erb
<div class="modal fade" id="thunderclap" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content thunderclap">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Sign Up for Thunderclap</h4>
      </div>
      <div class="modal-body">
        <iframe frameborder='0' height='540px' src='https://www.thunderclap.it/projects/44537-between-two-fires/embed' width='250px'></iframe>
      </div>
    </div>
  </div>
</div>

app/views/marknoce/about.html.erb
<%= render partial: "socialnav" %>
<%= render partial: "bottomsocialnav" %>
<div class="background-static">
  <div class="container">
    <section class="content">
        <h1>About Mark Noce</h1>
        <div class="line"></div>
        <br>
        <div class="about-text">
          I write historical fiction with a passion, and eagerly read everything from fantasy to literature. Born and raised in the San Francisco Bay Area, I'm an avid traveler and backpacker, particularly in Europe and North America. I earned my BA and MA from Cal Poly, San Luis Obispo, where I also met my beautiful wife. By day, I work as a Technical Writer, having spent much of my career at places like Google and Facebook. In addition to writing novels, I also write short fiction online. When not reading or writing, I'm probably listening to U2, sailing my dad’s boat, or gardening with my family.
          <br><br>
          My Queen Branwen Series is a collection of historical novels set in medieval Wales, published by St. Martin’s Press and Macmillan. To learn more about <u>Between Two Fires</u> and <u>Dark Winds Rising</u>, checkout my <%= link_to "Books", books_path %> section.
        </div>
        <div class="about-mark-photo col-sm-4">
        </div>
    </section>
    <div class="bottom-banner">
      <a href="https://www.amazon.com/Dark-Winds-Rising-Novel-Branwen/dp/1250072638/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=" target="_blank"><img src="assets/darkwindsbanner.jpg"></a>
    </div>
  </div>
</div>

app/views/marknoce/appearances.html.erb
<%= render partial: "socialnav" %>
<%= render partial: "bottomsocialnav" %>
<div class="background-static">
  <div class="container">
    <section class="content medium">
      <h1>Appearances</h1>
      <div class="line"></div>
      <br>
      <div>
        <h3><u>Upcoming Events</u></h3>
        <div class="appearances-side-panel">
          <a href="/books"><img id="appearances_book_art" class="book_img" src="assets/DarkWindsRising.jpg"/></a>
          <div class="dropdown fl-lt">
            <button onclick="myFunction()" class="dropbtn">Available Now!</button>
            <div id="myDropdown" class="dropdown-content">
              <a href="https://www.amazon.com/Dark-Winds-Rising-Novel-Branwen/dp/1250072638/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=" target="_blank">Amazon</a>
              <a href="https://www.amazon.com/Dark-Winds-Rising-Mark-Noce-ebook/dp/B0716WT9VS" target="_blank">Amazon Kindle</a>
              <a href="https://www.barnesandnoble.com/w/dark-winds-rising-mark-noce/1125377225?ean=9781250072634&st=PLA&sid=BNB_DRS_Core+Shopping+Books_00000000&2sid=Google_&sourceId=PLGoP75606" target="_blank">Barnes & Noble</a>
              <a href="https://www.barnesandnoble.com/w/dark-winds-rising-mark-noce/1125377225?ean=9781466884441&st=PLA&sid=NOK_DRS_NOOK+EBooks_00000000&2sid=Google_&sourceId=PLGoP75008" target="_blank">B&N Nook</a>
              <a href="https://itunes.apple.com/se/book/dark-winds-rising/id1237059301?l=en&mt=11" target="_blank">iTunes</a>
              <a href="http://www.indiebound.org/book/9781250072634" target="_blank">Indiebound</a>
            </div>
          </div>
        </div>
        <ul>
          <li>
            <h4>Sacramento, CA - The Avid Reader at Tower.</h4>
              <p>Saturday, Janurary 13, 2018 at 5pm</p>
              <p>New location near 20th on</p>
              <p><a href="https://goo.gl/maps/8FA2vS6P2ZL2" target="_blank">1945 Broadway<br>
              Sacramento, CA 95818</a></p>
          </li>
          <li>
            <h4>San Francisco, CA - The Mark Hopkins Hotel.</h4>
              <p>Friday, February 16, 2018 at 8am</p>
              <p>SFWC 2018</p>
              <p><a href="https://goo.gl/maps/UVMf7vUVo5M2" target="_blank">999 California Street<br>
              San Francisco, CA 94108</a></p>
          </li>
          <li>
            <h4>Sacramento, CA - Hyatt Regency Downtown.</h4>
              <p>Friday, March 10, 2018 at 5pm</p>
              <p>Authors on the Move</p>
              <p><a href="https://goo.gl/maps/W4Ur8bH9bs22" target="_blank">1209 L Street<br>
              Sacramento, CA 95841</a></p>
          </li>
          <li>
            <h4>San Luis Obispo, CA – Cuesta College.</h4>
              <p>Thursday-Saturday, September 27-29</p>
              <p>Central Coast Writer’s Conference</p>
              <p><a href="https://goo.gl/maps/FzF1TFeQei92" target="_blank">CA-1<br>
              San Luis Obispo, CA 93405</a></p>
          </li>
        </ul>
        <br>
        <h3><u>Past Events</u></h3>
        <ul>
          <li>
            <p>Burlingame Library - December 10, 2017</p>
          </li>
          <li>
            <p>California State Fair - July 15 & 22, 2017</p>
          </li>
          <li>
            <p>Authors on the Move - March 4, 2017</p>
          </li>
          <li>
            <p>Mark Hopkins Hotel - February 17, 2017</p>
          </li>
          <li>
            <p>Mills High School - January 26, 2016</p>
          </li>
          <li>
            <p>BDNA - December 15, 2016</p>
          </li>
          <li>
            <p>NaNoWriMo Session - November 13, 2016</p>
          </li>
          <li>
            <p>Mills High School - November 8, 2016</p>
          </li>
          <li>
            <p>Green Apple Books - November 6, 2016</p>
          </li>
          <li>
            <p>Barnes & Noble, San Luis Obispo - October 15, 2016</p>
          </li>
          <li>
            <p>The Avid Reader at Tower - September 3, 2016</p>
          </li>
          <li>
            <p>Burlingame Library - August 27, 2016</p>
          </li>
        </ul>
      </div>
    </section>
    <div class="bottom-banner">
      <a href="http://www.amazon.com/Between-Two-Fires-Mark-Noce/dp/125007262X" target="_blank"><img src="assets/BTFBanner.gif"></a>
    </div>
  </div>
</div>

app/views/marknoce/blog.html.erb
<script src="https://www.googleapis.com/blogger/v3/blogs/8458581324926992168/posts?callback=handleResponse&key=AIzaSyBPO9bgsBJ4Iw2R2Pcj8JZWrOMejLUz5AA"></script>
<%= render partial: "socialnav" %>
<%= render partial: "bottomsocialnav" %>
<div class="background">
  <div class="container">
    <section class="floaters content">
      <div class="right-sidebar">
        <div class="google-plus">
          <%= image_tag 'markblogpic.jpg', class: "blogpic" %>
          <h3><u>Mark Noce Stories</u></h3>
          <p>
            Welcome to my blog! Here is where I keep notes on all of my latest writing endeavors as well as other creative authors in the community.
          </p>
        </div>
        <div class="google-plus book-ad">
          <a href="/books"><img class="book_img" src="assets/BTFSquare.gif" width="236"/></a>
          <div class="dropdown">
            <button onclick="myFunction()" class="dropbtn">Available Now!</button>
            <div id="myDropdown" class="dropdown-content">
              <a href="http://www.amazon.com/Between-Two-Fires-Mark-Noce/dp/125007262X" target="_blank">Amazon</a>
              <a href="https://www.amazon.com/Between-Two-Fires-Mark-Noce-ebook/dp/B01BBXEZL4/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1466777586&sr=8-4&tag=smarturl-20" target="_blank">Amazon Kindle</a>
              <a href="http://www.barnesandnoble.com/w/between-two-fires-mark-noce/1122537645?ean=9781250072627" target="_blank">Barnes & Noble</a>
              <a href="http://www.barnesandnoble.com/w/between-two-fires-mark-noce/1122537645?ean=9781466884434" target="_blank">B&N Nook</a>
              <a href="https://itunes.apple.com/us/book/between-two-fires/id1080308282?mt=11" target="_blank">iTunes</a>
              <a href="http://www.indiebound.org/book/9781250072627" target="_blank">Indiebound</a>
            </div>
          </div>
        </div>
      </div>
      <div id="blogger">
      </div>
    </section>
    <div class="blogFooter">
      <a href="#" id="blogNext">Next 5</a>
    </div>
    <div class="bottom-banner">
      <a href="https://www.amazon.com/Dark-Winds-Rising-Novel-Branwen/dp/1250072638/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=" target="_blank"><img src="assets/darkwindsbanner.jpg"></a>
    </div>
  </div>
</div>

app/views/marknoce/books.html.erb
<%= render partial: "socialnav" %>
<%= render partial: "bottomsocialnav" %>
<div class="background">
  <div class="container">
    <section class="content medium">
      <h1>Novels</h1>
      <div class="line"></div>
      <br>
      <div>
      <img id="book_img1" class="book_img" src="assets/BetweenTwoFires.jpg" align="left" width="275"/>
      <h3><u>Between Two Fires</u></h3>
        <p>
          Saxon barbarians threaten to destroy medieval Wales. Lady Branwen becomes Wales’ last hope to unite their divided kingdoms when her father betroths her to a powerful Welsh warlord, the Hammer King.
        </p>
        <p>
          But this fledgling alliance is fraught with enemies from within and without as Branwen herself becomes the target of assassinations and courtly intrigue. A young woman in a world of fierce warriors, she seeks to assert her own authority and preserve Wales against the barbarians. But when she falls for a young hedge knight named Artagan her world threatens to tear itself apart. Caught between her duty to her people and her love of a man she cannot have, Branwen must choose whether to preserve her royal marriage or to follow her heart. Somehow she must save her people and remain true to herself, before Saxon invaders and a mysterious traitor try to destroy her.
        </p>
        <div class="dropdown">
          <button onclick="myFunction()" class="dropbtn">Available Now!</button>
          <div id="myDropdown" class="dropdown-content">
            <a href="http://www.amazon.com/Between-Two-Fires-Mark-Noce/dp/125007262X" target="_blank">Amazon</a>
            <a href="https://www.amazon.com/Between-Two-Fires-Mark-Noce-ebook/dp/B01BBXEZL4/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1466777586&sr=8-4&tag=smarturl-20" target="_blank">Amazon Kindle</a>
            <a href="http://www.barnesandnoble.com/w/between-two-fires-mark-noce/1122537645?ean=9781250072627" target="_blank">Barnes & Noble</a>
            <a href="http://www.barnesandnoble.com/w/between-two-fires-mark-noce/1122537645?ean=9781466884434" target="_blank">B&N Nook</a>
            <a href="https://itunes.apple.com/us/book/between-two-fires/id1080308282?mt=11" target="_blank">iTunes</a>
            <a href="http://www.indiebound.org/book/9781250072627" target="_blank">Indiebound</a>
          </div>
        </div>
        <br><br>
        <p>
          “A fast-paced read that has a wonderfully visual style and some memorable characters. Mark Noce combines Welsh history with a touch of folkloric magic in this promising debut novel. Lady Branwen is a strong and engaging narrator and the turbulent setting of early medieval Wales makes a fine backdrop for an action-packed story.”
        </p>
        <p>
          &nbsp;&nbsp;&nbsp;&nbsp;<i>– Juliet Marillier, Bestselling author of Daughter of the Forest and Wolfskin</i>
        </p>
        <br>
        <p>
          “A spirited ride through a turbulent slice of Welsh history!”
        </p>
        <p>
          &nbsp;&nbsp;&nbsp;&nbsp;<i>– Paula Brackston, NYT Bestselling author of The Witch’s Daughter</i>
        </p>
        <br>
        <p>
          Check out chapter 1 of the audiobook below:
        </p>
        <a id="darkwinds"></a>
        <iframe width="100%" height="100" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/280006197&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
      <br><br>
      <div>
      <div class="book-side-panel">
        <img class="book_img" id="dark-winds-img" src="assets/DarkWindsRising.jpg" width="300" />
      </div>
      <h3><u>Dark Winds Rising</u></h3>
        <p>
          Queen Branwen finds her world once again turned upside down as Pictish raiders harry the shores of her kingdom. Rallying her people once more, she must face her most dangerous foe yet, the Queen of the Picts. Ruthless and cunning, the Pictish Queen turns the Welsh against each other in a bloody civil war, and Branwen must attempt to stop her before her country threatens to tear itself apart. All the while Branwen is heavy with child, and finds her young son’s footsteps dogged by a mysterious assassin. Branwen must somehow defeat the Picts and save her people before the Pictish Queen and a mysterious assassin threaten to destroy their lives from the inside out.
        </p>
        <br>
        <p class="pre-order">
          <a href="https://www.amazon.com/Dark-Winds-Rising-Mark-Noce/dp/1250072638" target="_blank">Available Now!</a>
        </p>
      </div>
      <br><br><br><br>
      <div class="line"></div>
      <br>
      <h1>Short Stories</h1>

      <h3>London Bound</h3>
        <p>
          “London Bound” offers a fictional account of my very real experiences during the July 7, 2005 London Bombings. Published by Cal Poly’s Moebius Magazine, “London Bound” describes the experiences of an American backpacker stranded on a train with several strangers when the terrorists attack. Read my short-story <a href="http://digitalcommons.calpoly.edu/moebius/vol5/iss1/27/" target="_blank">“London Bound”</a> online or view the entire <a href="http://digitalcommons.calpoly.edu/moebius/vol5/iss1/" target="_blank"><u>Moebius Magazine</u></a> . My story is humbly dedicated to those who lost their lives that day.
        </p>
      <h3>Flash Fiction</h3>

      Three of my flash fiction pieces have been published at Every Day Fiction. Each story is under 1,000 words in length, and is set in contemporary times. Check out the links below.

      - <a href="http://www.everydayfiction.com/meet-me-at-the-waterfront-by-mark-noce/" target="_blank"><h4>“Meet Me at the Waterfront“</h4></a>
        <p>
          A magical-realism piece, "Meet Me at the Waterfront" examines a boy standing up to the schoolyard bully and what happens when he learns something both about himself and the boy he fears.
        </p>
      <a href="http://www.everydayfiction.com/chronicles-of-the-sfpd-by-mark-noce/"><h4>“Chronicles of the SFPD”</h4></a>
        <p>
          A contemporary noir story set in San Francisco's seedy Tenderloin, Chronicles of the SFPD follows a newbie police officer trying to make good on the tough streets of a modern city.
        </p>


      <a href="http://www.everydayfiction.com/disturbance-at-apartment-408-by-mark-noce/"><h4>“Disturbance at Apartment 408”</h4></a>
        <p>
          Another short noir story, "Disturbance at Apartment 408" shows us what happens when a greenhorn police officer has to deal with the unpredictable entanglements of a disturbance-call gone awry.
        </p>
    </section>
    <div class="bottom-banner">
      <a href="http://www.amazon.com/Between-Two-Fires-Mark-Noce/dp/125007262X" target="_blank"><img src="assets/BTFBanner.gif"></a>
    </div>
  </div>
</div>